platform :ios, '12.0'

# Specify which schemes refer to the debug configuration
project 'RetenoExample', {
  'Debug' => :debug,
  'Staging-Debug' => :debug,
  'Production-Debug' => :debug
}

use_frameworks!

target 'RetenoExample' do
  use_frameworks!

  pod 'Swinject', '~> 2.7.1'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Reteno', '1.5.1'
  pod 'FirebaseMessaging'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '7.28.0'
  
  target 'NotificationServiceExtension' do
    use_frameworks!

    pod 'Reteno', '1.5.1'

  end
  
  target 'NotificationContentExtension' do
    use_frameworks!

    pod 'Reteno', '1.5.1'

  end
  
  target 'RetenoExampleTests' do
    use_frameworks!

    pod 'Reteno', '1.5.1'
    pod 'OHHTTPStubs/Swift'

  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        end
    end
end
